global.rpg = {
emoticon(string) {
string = string.toLowerCase()
let emot = {
level: '🧬 Nivel',
limit: '💎 Diamante',
exp: '⚡ Experiencia',
bank: '🏦 Banco',
diamond: '💎 Diamante',
health: '❤️ Salud',
kyubi: '🌀 Magia',
joincount: '🪙 Token',
emerald: '💚 Esmeralda',
stamina: '✨ Energía',
role: '💪 Rango',
premium: '🎟️ Premium',
pointxp: '📧 Puntos Exp',
gold: '👑 Oro',
trash: '🗑 Basura',
crystal: '🔮 Cristal',
intelligence: '🧠 Inteligencia',
string: '🕸️ Cuerda',
keygold: '🔑 Llave de Oro',
keyiron: '🗝️ Llave de Hierro',
emas: '🪅 Piñata',
fishingrod: '🎣 Caña de Pescar',
gems: '🍀 Gemas',
magicwand: '⚕️ Varita Mágica',
mana: '🪄 Hechizo',
agility: '🤸‍♂️ Agilidad',
darkcrystal: '♠️ Cristal Oscuro',
iron: '⛓️ Hierro',
rock: '🪨 Roca',
potion: '🥤 Poción',
superior: '💼 Superior',
robo: '🚔 Robo',
upgrader: '🧰 Aumentar Mejora',
wood: '🪵 Madera',
strength: '🦹‍ ♀️ Fuerza',
arc: '🏹 Arco',
armor: '🥼 Armadura',
bow: '🏹 Super Arco',
pickaxe: '⛏️ Pico',
sword: '⚔️ Espada',
common: '📦 Caja Común',
uncoommon: '🥡 Caja Poco Común',
mythic: '🗳️ Caja Mítico',
legendary: '🎁 Caja Legendaria',
petFood: '🍖 Alimento para Mascota',
pet: '🍱 Caja para Mascota',
semillasdeuva: '🍇 Semilla de Uva',
semillasdemanzana: '🍎 Semilla de Manzana',
semillasdenaranja: '🍊 Semillas de naranja',
semillasdemango: '🥭 Semilla de Mango',
semillasdeplatano: '🍌 Semillas de Plátano',
pollo: '🐓 Pollo',
cerdo: '🐖 Puerco',
Jabali: '🐗 Jabali',
toro: '🐃 Toro',
cocodrilo: '🐊 Cocodrilo',
gato: '🐈 Gato',
centauro: '🐐 Centauro',
chicken: '🐓 Pollo',
cow: '🐄 Vaca', 
dog: '🐕 Perro',
dragon: '🐉 Dragón',
elefante: '🐘 Elefante',
zorro: '🦊 Zorro',
jirafa: '🦒 Jirafa',
griffin: '🦅 Ave',
horse: '🐎 Caballo',
kambing: '🐐 Cabra',
kerbau: '🐃 Búfalo',
lion: '🦁 León',
money: '🪙 ANIMXCoins',
monyet: '🐒 Mono',
panda: '🐼 Panda',
snake: '🐍 Serpiente',
phonix: '🕊️ Fénix',
rhinoceros: '🦏 Rinoceronte',
wolf: '🐺 Lobo',
tiger: '🐅 Tigre',
cumi: '🦑 Calamar',
udang: '🦐 Camarón',
ikan: '🐟 Pez',
fideos: '🍝 Fideos',
ramuan: '🧪 Ingrediente NOVA',
knife: '🔪 Cuchillo'
}
let results = Object.keys(emot).map(v => [v, new RegExp(v, 'gi')]).filter(v => v[1].test(string))
if (!results.length) return ''
else return emot[results[0][0]]
}}
global.rpgg = { //Solo emojis 
emoticon(string) {
string = string.toLowerCase()
let emott = {
level: '🧬',
limit: '💎',
exp: '⚡',
bank: '🏦',
diamond: '💎+',
health: '❤️',
kyubi: '🌀',
joincount: '🪙',
emerald: '💚',
stamina: '✨',
role: '💪',
premium: '🎟️',
pointxp: '📧',
gold: '👑',
trash: '🗑',
crystal: '🔮',
intelligence: '🧠',
string: '🕸️',
keygold: '🔑',
keyiron: '🗝️',
emas: '🪅',
fishingrod: '🎣',
gems: '🍀',
magicwand: '⚕️',
mana: '🪄',
agility: '🤸‍♂️',
darkcrystal: '♠️',
iron: '⛓️',
rock: '🪨',
potion: '🥤',
superior: '💼',
robo: '🚔',
upgrader: '🧰',
wood: '🪵',
strength: '🦹‍ ♀️',
arc: '🏹',
armor: '🥼',
bow: '🏹',
pickaxe: '⛏️',
sword: '⚔️',
common: '📦',
uncoommon: '🥡',
mythic: '🗳️',
legendary: '🎁',
petFood: '🍖',
pet: '🍱',
semillasdeuva: '🍇',
semillasdemanzana: '🍎',
semillasdenaranja: '🍊',
semillasdemango: '🥭',
semillasdeplatano: '🍌',
pollo: '🐓',
cerdo: '🐖',
Jabali: '🐗',
toro: '🐃',
cocodrilo: '🐊',
gato: '🐈',
centauro: '🐐',
chicken: '🐓',
cow: '🐄', 
dog: '🐕',
dragon: '🐉',
elefante: '🐘',
zorro: '🦊',
jirafa: '🦒',
griffin: '🦅', 
horse: '🐎',
kambing: '🐐',
kerbau: '🐃',
lion: '🦁',
money: '🪙',
monyet: '🐒',
panda: '🐼',
snake: '🐍',
phonix: '🕊️',
rhinoceros: '🦏',
wolf: '🐺',
tiger: '🐅',
cumi: '🦑',
udang: '🦐',
ikan: '🐟',
fideos: '🍝',
ramuan: '🧪',
knife: '🔪'
}
let results = Object.keys(emott).map(v => [v, new RegExp(v, 'gi')]).filter(v => v[1].test(string))
if (!results.length) return ''
else return emott[results[0][0]]
}}
global.rpgshop = { //Tienda
emoticon(string) {
string = string.toLowerCase()
let emottt = {
exp: '⚡ Experiencia',
limit: '💎 Diamante',
diamond: '💎 Diamante',
joincount: '🪙 Token',
emerald: '💚 Esmeralda',
berlian: '♦️ Joya',
kyubi: '🌀 Magia',
gold: '👑 Oro',
money: '🪙 ANIMXCoins',
tiketcoin: '🎫 ANI Tickers',
stamina: '✨ Energía',
potion: '🥤 Poción',
aqua: '💧 Agua',
trash: '🗑 Basura',
wood: '🪵 Madera',
rock: '🪨 Roca',
batu: '🥌 Piedra',
string: '🕸️ Cuerda',
iron: '⛓️ Hierro',
coal: '⚱️ Carbón',
botol: '🍶 Botella',
kaleng: '🥫 Lata',
kardus: '🪧 Cartón',
eleksirb: '💡 Electricidad',
emasbatang: '〽️ Barra de Oro',
emasbiasa: '🧭 Oro Común',
rubah: '🦊🌫️ Zorro Grande',
sampah: '🗑🌫️ Super Basura',
serigala: '🐺🌫️ Super Lobo',
kayu: '🛷 Super Madera',
sword: '⚔️ Espada',
umpan: '🪱 Carnada', 
healtmonster: '💵 Billetes',
emas: '🪅 Piñata',
pancingan: '🪝 Gancho',
pancing: '🎣 Caña de Pescar',
common: '📦 Caja Común',
uncoommon: '🥡 Caja Poco Común',
mythic: '🗳️ Caja Mítica',
pet: '📫 Caja de Mascotas',//?
gardenboxs: '💐 Caja de Jardinería',//?
legendary: '🎁 Caja Legendaria',
anggur: '🍇 Uva',
apel: '🍎 Manzana',
jeruk: '🍊 Naranja',
mangga: '🥭 Mango',
pisang: '🍌 Platano',
semillasdeuva: '🌾🍇 Semillas de uva',
semillasdemanzana: '🌾🍎 Semillas de manzana',
semillasdenaranja: '🌾🍊 Semillas de naranja',
semillasdemango: '🌾🥭 Semillas de Mango',
semillasdeplatano: '🌾🍌 Semillas de plátano',
centauro: '🐐 Centauro',
griffin: '🦅 Ave',
kucing: '🐈 Gato',
naga: '🐉 Dragón',
zorro: '🦊 Zorro',
kuda: '🐎 Caballo',
phonix: '🕊️ Fénix',
wolf: '🐺 Lobo',
anjing: '🐶 Perro',
petFood: '🍖 Alimento para Mascota', //?
makanancentaur: '🐐🥩 Comida de Centauro',
makanangriffin: '🦅🥩 Comida de Ave',
makanankyubi: '🌀🥩 Comida Mágica',
makanannaga: '🐉🥩 Comida de Dragón',
makananpet: '🍱🥩 Alimentos de mascotas',
makananphonix: '🕊️🥩 Comida de Fénix'
}
let results = Object.keys(emottt).map(v => [v, new RegExp(v, 'gi')]).filter(v => v[1].test(string))
if (!results.length) return ''
else return emottt[results[0][0]]
}}
global.rpgshopp = { //Tienda
emoticon(string) {
string = string.toLowerCase()
let emotttt = {
exp: '⚡',
limit: '💎',
diamond: '💎+',
joincount: '🪙',
emerald: '💚',
berlian: '♦️',
kyubi: '🌀',
gold: '👑',
money: '🪙',
tiketcoin: '🎫',
stamina: '✨',
potion: '🥤',
aqua: '💧',
trash: '🗑',
wood: '🪵',
rock: '🪨',
batu: '🥌',
string: '🕸️',
iron: '⛓️',
coal: '⚱️',
botol: '🍶',
kaleng: '🥫',
kardus: '🪧',
eleksirb: '💡',
emasbatang: '〽️',
emasbiasa: '🧭',
rubah: '🦊🌫️',
sampah: '🗑🌫️',
serigala: '🐺🌫️',
kayu: '🛷',
sword: '⚔️',
umpan: '🪱', 
healtmonster: '💵',
emas: '🪅',
pancingan: '🪝',
pancing: '🎣',
common: '📦',
uncoommon: '🥡',
mythic: '🗳️',
pet: '📫',//?
gardenboxs: '💐',//?
legendary: '🎁',
anggur: '🍇',
apel: '🍎',
jeruk: '🍊',
mangga: '🥭',
pisang: '🍌',
semillasdeuva: '🌾🍇',
semillasdemanzana: '🌾🍎',
semillasdenaranja: '🌾🍊',
semillasdemango: '🌾🥭',
semillasdeplatano: '🌾🍌',
centauro: '🐐',
griffin: '🦅',
kucing: '🐈',
naga: '🐉',
zorro: '🦊',
kuda: '🐎',
phonix: '🕊️',
wolf: '🐺',
anjing: '🐶',
petFood: '🍖', //?
makanancentaur: '🐐🥩',
makanangriffin: '🦅🥩',
makanankyubi: '🌀🥩',
makanannaga: '🐉🥩',
makananpet: '🍱🥩',
makananphonix: '🕊️🥩'
}
let results = Object.keys(emotttt).map(v => [v, new RegExp(v, 'gi')]).filter(v => v[1].test(string))
if (!results.length) return ''
else return emotttt[results[0][0]]
}}	
